[package]
name = "realms"
version = "0.1.0"
authors = ["Jonathan Kieling <code@j0na.net>"]

[dependencies]
serde = "*"
serde_derive = "*"
rand = "*"
bincode = "*"
tui = "*"
termion = "*"
chrono = "*"
itertools = "*"